apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: inside-conf
spec:
  config:  |-
    { 
      "cniVersion": "0.3.0",
      "type": "macvlan", 
      "master": "eno2", 
      "mode": "bridge",
      "ipam": { 
          "type": "host-local", 
          "subnet": "10.0.0.0/24", 
          "rangeStart": "10.0.0.1",
          "rangeEnd": "10.0.0.5", 
          "routes": [ 
              { "dst": "0.0.0.0/0" } 
                ], 
          "gateway":"10.0.0.10" 
              }
    }
