apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: outside-conf
spec:
  config:  |-
    { 
      "cniVersion": "0.3.0", 
      "type": "macvlan", 
      "master": "eno1", 
      "mode": "bridge",
      "ipam": { 
          "type": "host-local", 
          "subnet": "192.168.0.0/24", 
          "rangeStart": "192.168.0.200",
          "rangeEnd": "192.168.0.216",
          "routes": [ 
              { "dst": "0.0.0.0/0" }
                ], 
          "gateway":"192.168.0.1" 
              }
    }