kind: Service
apiVersion: v1
metadata:
  name: sip
  namespace: sip
  labels:
    app: sip
spec:
  ports:
    - name: http-tcp
      protocol: TCP
      port: 5060
      targetPort: 5060
  selector:
    app: sip
  type: ClusterIP